{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-service
  port:
    targetPort: http
  tls:
    termination: edge
{{- end }}
